### ISSUE TITLE
No available storage method found

### ISSUE THREAD

**Issue by rodolfocop** [Alorel/ngforage#68]
Hi, currently I'm using NgForage 2.0.0 and LocalForage 1.5.0 I'm navigating throught pages I'm getting error like :

```
core.js:1449 ERROR Error: Uncaught (in promise): Error: No available storage method found.
Error: No available storage method found
```
image below

![capturar](https://user-images.githubusercontent.com/13018533/40259400-edd58b26-5ac3-11e8-9cc9-f85371ca4865.JPG)

I'am using this configuration
```
constructor(ngfConfig: NgForageConfig) {
ngfConfig.configure({
      name: 'itens',
      storeName: 'dbitens',
      driver: NgForageConfig.DRIVER_INDEXEDDB
    });
}
```
Angular-Cli : 1.7.3
@angular : 5.2.5

**Comment by Alorel** [comment]
Hey. There were a few bugs left in the 2.0.0 version and it's been deprecated for a while - could you upgrade to 2.2.1 please and see if the issue persists?

I see you're using Chrome which should definitely have IndexedDB available, so this is strange. Could you try:

1. Setting the driver to localStorage just to see if it works then.
2. Passing the driver as an array to see if that fixes the problem (in which case I'll know exactly what to fix)? I.e. instead of 

```typescript
cfg.configure({driver: NgForageConfig.DRIVER_INDEXEDDB});
```

you'd do

```typescript
cfg.configure({driver: [NgForageConfig.DRIVER_INDEXEDDB]});
```

**Comment by rodolfocop** [comment]
Hi, @Alorel  thanks for response. 

Update version this resolved my problem, i will leave a default setting as requested.
