### ISSUE TITLE
prod build fails - 'could not resolve ../imports/localforage/'

### ISSUE THREAD

**Issue by grreeenn** [Alorel/ngforage#74]
Hello,

Although the dev build passes ok, building with --prod flag causes the following error:
```
ERROR in Error during template compile of 'AppModule'
  Could not resolve ../imports/localforage relative to /home/green/develop/angular6-imageslider-interview-app/node_modules/ngforage/ngforage.d.ts. in 'NgForageConfig'
    'NgForageConfig' contains the error at ../ngforage/ngforage.ts(19,53).
```
Ubuntu, Angular&CLI 6.0.8
clean app on default configs; am I missing something?

Thanks!

**Comment by grreeenn** [comment]
the issue has fixed itself. Please close the issue :)

**Comment by Alorel** [comment]
Hey, sorry for the late reply as I was unavailable during the weekend. Glad everything's resolved.

**Comment by armory09** [comment]
I'm getting the same error, @grreeenn how did you solved it?

**Comment by grreeenn** [comment]
hi @armory09,
when I think about it now, the only thing I did was to change the default drivers with the string "asyncStorage", as it's shown in the [demo](https://alorel.github.io/ngforage/). Everything else remained the same...

**Comment by armory09** [comment]
@grreeenn that do the trick, Thank you.

**Comment by Alorel** [comment]
@grreeenn That's really odd. I've tried to reproduce the issue with the latest version of angular, ngforage and localforage and have been unsuccessful.

Generally you should

1. Not hardcode strings. `asyncStorage` comes from a constant in localForage and may break your application during an upgrade.
1. Provide an array of storage engines so localForage has a fallback engine to use if the previous one is unavailable. Otherwise, you should always ensure that IndexedDB is available, which would involve including a polyfill for ancient browsers.

**Comment by grreeenn** [comment]
@Alorel have you tried ng serve --prod?

**Comment by lukeiszed** [comment]
I have the same problem, cannot build with --prod flag, so the @grreeenn solution is the only option available?

**Comment by metalelf0** [comment]
I'm having the same issue. @grreeenn fix does the trick, though it's not very clear why.
